import type { ActivityCategory, SchoolPersona, Activity, Opportunity, MentorProfile } from '@/types'

export const CATEGORY_LABELS: Record<ActivityCategory, string> = {
  scholarship: 'Học bổng',
  competition: 'Cuộc thi',
  extracurricular: 'Ngoại khoá',
  research: 'Nghiên cứu',
  self_learning: 'Tự học',
  green_ethics: 'Green Ethics',
}

export const CATEGORY_COLORS: Record<ActivityCategory, string> = {
  scholarship: 'bg-purple-100 text-purple-700',
  competition: 'bg-amber-100 text-amber-700',
  extracurricular: 'bg-blue-100 text-blue-700',
  research: 'bg-rose-100 text-rose-700',
  self_learning: 'bg-cyan-100 text-cyan-700',
  green_ethics: 'bg-green-100 text-green-700',
}

export const TRUST_LABELS: Record<number, string> = {
  1: 'Tự khai',
  2: 'Xác thực GV',
  3: 'Chứng chỉ',
}

export const TRUST_COLORS: Record<number, string> = {
  1: 'bg-gray-100 text-gray-600',
  2: 'bg-blue-100 text-blue-700',
  3: 'bg-amber-100 text-amber-700',
}

export const CATEGORY_WEIGHT: Record<string, Record<ActivityCategory, number>> = {
  cntt: {
    scholarship: 1.2,
    competition: 1.5,
    extracurricular: 1.0,
    research: 1.5,
    self_learning: 1.2,
    green_ethics: 1.0,
  },
  toan_thong_ke: {
    scholarship: 1.2,
    competition: 1.5,
    extracurricular: 1.0,
    research: 1.5,
    self_learning: 1.0,
    green_ethics: 0.8,
  },
}

export const TRUST_WEIGHT: Record<number, number> = { 1: 0.5, 2: 1.0, 3: 1.5 }
export const MAX_OCS_SCORE = 10 * 5 * 1.5 * 1.5 // 112.5

export const BIG6_SCHOOLS: SchoolPersona[] = [
  {
    school_id: 'vinuni',
    school_name: 'Đại học VinUni',
    short_name: 'VinUni',
    min_sat: 1450,
    min_gpa: 9.0,
    min_ielts: 6.5,
    has_interview: true,
    min_portfolio_activities: 6,
    preferred_categories: ['competition', 'research'],
    persona_description: 'Ưu tiên học sinh xuất sắc, SAT cao, Portfolio chất lượng và phỏng vấn AACC.',
  },
  {
    school_id: 'hust',
    school_name: 'ĐH Bách Khoa HN',
    short_name: 'HUST',
    min_sat: 1200,
    min_gpa: 8.0,
    min_ielts: 5.0,
    has_interview: false,
    min_portfolio_activities: 3,
    preferred_categories: ['competition', 'research', 'extracurricular'],
    persona_description: 'Xét tuyển tài năng: GPA ≥ 8.0 mỗi năm. Cộng điểm hoạt động ngoại khoá.',
  },
  {
    school_id: 'usth',
    school_name: 'Đại học USTH',
    short_name: 'USTH',
    min_sat: 1100,
    min_gpa: 7.5,
    min_ielts: 5.0,
    has_interview: true,
    min_portfolio_activities: 3,
    preferred_categories: ['research', 'competition'],
    persona_description: 'SAT ≥ 1100, IELTS ≥ 5.0. Nộp hồ sơ năng lực + phỏng vấn.',
  },
  {
    school_id: 'vju',
    school_name: 'Đại học Việt Nhật',
    short_name: 'VJU',
    min_sat: 1100,
    min_gpa: 7.0,
    min_ielts: 4.0,
    has_interview: true,
    min_portfolio_activities: 2,
    preferred_categories: ['extracurricular', 'research'],
    persona_description: 'GPA xếp loại Khá trở lên. Đánh giá qua phỏng vấn và bài luận.',
  },
  {
    school_id: 'fpt',
    school_name: 'Đại học FPT',
    short_name: 'FPT',
    min_sat: null,
    min_gpa: 7.0,
    min_ielts: 5.0,
    has_interview: false,
    min_portfolio_activities: 2,
    preferred_categories: ['self_learning', 'competition', 'extracurricular'],
    persona_description: 'Linh hoạt, ưu tiên thực chiến và chứng chỉ công nghệ.',
  },
  {
    school_id: 'swinburne',
    school_name: 'Swinburne Việt Nam',
    short_name: 'Swinburne',
    min_sat: null,
    min_gpa: 7.0,
    min_ielts: 6.0,
    has_interview: false,
    min_portfolio_activities: 2,
    preferred_categories: ['extracurricular', 'scholarship'],
    persona_description: 'IELTS ≥ 6.0. GPA ≥ 7.0. Minh chứng ngoại khoá để xét học bổng.',
  },
]

export const DEMO_ACTIVITIES: Activity[] = [
  {
    activity_id: '1',
    user_id: 'demo',
    category: 'competition',
    title: 'NASA Space Apps Challenge 2024',
    star_situation: 'Tham gia cuộc thi hackathon toàn cầu NASA Space Apps Challenge năm 2024, đội 5 người sinh viên và học sinh THPT từ Hà Nội.',
    star_task: 'Phụ trách phần Machine Learning để phân tích dữ liệu vệ tinh NASA dự đoán biến đổi khí hậu khu vực Đồng bằng Sông Cửu Long.',
    star_action: 'Xây dựng pipeline ML với Python/TensorFlow, thu thập và xử lý 50GB dữ liệu vệ tinh MODIS, huấn luyện mô hình CNN phát hiện ngập lụt với độ chính xác 91%. Thiết kế dashboard trực quan hóa bằng React + D3.js.',
    star_result: 'Top 10 Global (từ 57,000+ đội tham dự). Được NASA công nhận giải "Best Use of Data". Báo cáo được chia sẻ tại hội nghị COP28.',
    trust_tier: 3,
    trust_verified_by: 'NASA Official Certificate',
    tech_tags: ['Python', 'TensorFlow', 'Machine Learning', 'Data Analysis', 'React'],
    base_score: 5,
    slot_order: 1,
    artifact_url: 'https://github.com/example/nasa-space-apps',
    created_at: '2024-10-15T00:00:00Z',
  },
  {
    activity_id: '2',
    user_id: 'demo',
    category: 'scholarship',
    title: 'UWC Selection — Top 40/1040',
    star_situation: 'Tham dự vòng tuyển chọn UWC Việt Nam 2024 với 1040 ứng viên từ toàn quốc.',
    star_task: 'Vượt qua 4 vòng: hồ sơ, bài luận, phỏng vấn nhóm, phỏng vấn cá nhân với ban tuyển chọn quốc tế.',
    star_action: 'Chuẩn bị hồ sơ trong 3 tháng, viết 5 bài luận thể hiện tư duy phản biện về giáo dục STEM. Thực hành phỏng vấn 20+ lần, nghiên cứu sứ mệnh UWC và liên kết với các dự án cộng đồng đã làm.',
    star_result: 'Lọt vào Top 40 ứng viên xuất sắc nhất (tỷ lệ 3.8%). Nhận học bổng bán phần trị giá 15,000 USD.',
    trust_tier: 3,
    trust_verified_by: 'UWC Official Certificate',
    tech_tags: ['Leadership', 'Communication'],
    base_score: 5,
    slot_order: 2,
    artifact_url: null,
    created_at: '2024-04-01T00:00:00Z',
  },
  {
    activity_id: '3',
    user_id: 'demo',
    category: 'extracurricular',
    title: 'CLB Robotics Ams — Trưởng CLB',
    star_situation: 'CLB Robotics trường THPT Ams, thành lập 2021 với 8 thành viên ban đầu.',
    star_task: 'Được bầu làm Trưởng CLB nhiệm kỳ 2023-2024, chịu trách nhiệm toàn bộ hoạt động kỹ thuật và tổ chức.',
    star_action: 'Phát triển CLB từ 8 lên 35 thành viên. Tổ chức 12 workshop kỹ thuật về Arduino, ROS, Computer Vision. Dẫn đội thi VEX Robotics Regional 2023. Xây dựng curriculum robotics cho học sinh lớp 10 mới.',
    star_result: 'CLB đạt giải Nhì VEX Regional 2023. 85% thành viên tốt nghiệp có portfolio dự án robotics. 3 thành viên được nhận vào VinUni, HUST.',
    trust_tier: 2,
    trust_verified_by: 'teacher@ams.edu.vn',
    tech_tags: ['Arduino', 'Leadership', 'Robotics', 'C++'],
    base_score: 4,
    slot_order: 3,
    artifact_url: null,
    created_at: '2023-09-01T00:00:00Z',
  },
  {
    activity_id: '4',
    user_id: 'demo',
    category: 'research',
    title: 'Paper: AI Bias nhận diện khuôn mặt tại VN',
    star_situation: 'Nghiên cứu độc lập về vấn đề AI Bias trong các hệ thống nhận diện khuôn mặt thương mại khi áp dụng ở Việt Nam, năm học 2023-2024.',
    star_task: 'Điều tra mức độ bias của 3 API nhận diện khuôn mặt (AWS Rekognition, Azure Face API, Google Vision) với dữ liệu người Việt.',
    star_action: 'Thu thập dataset 2000 ảnh đa dạng về giới tính, vùng miền, độ tuổi người Việt. Chạy benchmark trên 3 API, phân tích kết quả bằng Python/pandas. Viết báo cáo 25 trang theo chuẩn ACM. Được mentor là GS ĐH Bách Khoa hướng dẫn.',
    star_result: 'Paper được chấp nhận tại hội thảo Khoa học Thanh niên HUST 2024. Phát hiện tỷ lệ lỗi cao hơn 23% với gương mặt phụ nữ miền Nam so với nam giới miền Bắc.',
    trust_tier: 2,
    trust_verified_by: 'professor@hust.edu.vn',
    tech_tags: ['Python', 'Research', 'AI Ethics', 'Data Analysis', 'Machine Learning'],
    base_score: 4,
    slot_order: 4,
    artifact_url: 'https://github.com/example/ai-bias-vn',
    created_at: '2024-03-01T00:00:00Z',
  },
  {
    activity_id: '5',
    user_id: 'demo',
    category: 'extracurricular',
    title: 'Code for Kids — Dạy 200+ học sinh tiểu học',
    star_situation: 'Chương trình tình nguyện dạy lập trình cơ bản cho học sinh tiểu học trường vùng ngoại thành Hà Nội, hè 2023.',
    star_task: 'Thiết kế curriculum và dạy trực tiếp lập trình Scratch + Python cơ bản cho 200+ học sinh lớp 4-5.',
    star_action: 'Xây dựng 8 bài học gamified với Scratch, tạo 30+ mini-game giáo dục. Tập huấn 5 tình nguyện viên khác. Tổ chức mini hackathon cuối khóa để học sinh showcase project.',
    star_result: '215 học sinh hoàn thành khóa học. 89% phụ huynh hài lòng (khảo sát). 12 học sinh tiếp tục học Python nâng cao. Được VnExpress đưa tin.',
    trust_tier: 1,
    trust_verified_by: null,
    tech_tags: ['Teaching', 'Social Impact', 'Python', 'Scratch'],
    base_score: 3,
    slot_order: 5,
    artifact_url: null,
    created_at: '2023-07-01T00:00:00Z',
  },
  {
    activity_id: '6',
    user_id: 'demo',
    category: 'self_learning',
    title: 'Coursera Deep Learning Specialization — 100%',
    star_situation: 'Tự học khóa Deep Learning Specialization của Andrew Ng trên Coursera, từ tháng 11/2023 đến 2/2024.',
    star_task: 'Hoàn thành 5 khóa học: Neural Networks, Improving Deep NNs, Structuring ML Projects, CNN, Sequence Models.',
    star_action: 'Học 4-6 tiếng/tuần trong 3 tháng. Làm đầy đủ assignments bằng Python/NumPy/TensorFlow. Xây dựng 5 dự án thực hành bao gồm: nhận diện chữ số viết tay, phân tích cảm xúc văn bản, dịch máy seq2seq.',
    star_result: 'Hoàn thành 100% với điểm trung bình 96.2/100. Chứng chỉ từ DeepLearning.AI. Áp dụng trực tiếp vào dự án NASA Space Apps.',
    trust_tier: 1,
    trust_verified_by: null,
    tech_tags: ['Deep Learning', 'TensorFlow', 'Python', 'Neural Networks'],
    base_score: 3,
    slot_order: 6,
    artifact_url: 'https://coursera.org/verify/example',
    created_at: '2024-02-28T00:00:00Z',
  },
  {
    activity_id: '7',
    user_id: 'demo',
    category: 'competition',
    title: 'Olympic Tin học cấp Tỉnh — Giải Ba',
    star_situation: 'Kỳ thi Olympic Tin học tỉnh Hà Nội năm 2023, 180 thí sinh từ các trường THPT chuyên.',
    star_task: 'Thi đấu phần lập trình thuật toán bằng C++, giải 5 bài trong 3 tiếng.',
    star_action: 'Ôn luyện 6 tháng với sách giáo khoa và Codeforces, tập trung vào: DP, Graph, Segment Tree, Binary Search. Giải 200+ bài trên Codeforces rating 1650+.',
    star_result: 'Đạt Giải Ba tỉnh Hà Nội. Giải được 4/5 bài, điểm số 280/400.',
    trust_tier: 3,
    trust_verified_by: 'Sở GD&ĐT Hà Nội',
    tech_tags: ['Algorithms', 'C++', 'Data Structures', 'Competitive Programming'],
    base_score: 4,
    slot_order: 7,
    artifact_url: null,
    created_at: '2023-12-10T00:00:00Z',
  },
  {
    activity_id: '8',
    user_id: 'demo',
    category: 'competition',
    title: 'Kaggle ML Competition — Top 15%',
    star_situation: 'Tham gia cuộc thi Kaggle "Tabular Playground Series" tháng 2/2024 với 3000+ đội tham dự.',
    star_task: 'Xây dựng mô hình dự đoán giá nhà từ dữ liệu tabular với 200+ features.',
    star_action: 'Feature engineering với pandas, thử nghiệm XGBoost, LightGBM, Neural Networks. Ensemble stacking 3 models. Tối ưu hyperparameters bằng Optuna. Tuần làm việc 15+ tiếng.',
    star_result: 'Đạt Top 15% (450/3100 đội). RMSE score: 0.12847, cải thiện từ baseline 0.21.',
    trust_tier: 2,
    trust_verified_by: 'Kaggle Public Leaderboard',
    tech_tags: ['Python', 'Machine Learning', 'XGBoost', 'Data Science', 'Feature Engineering'],
    base_score: 4,
    slot_order: 8,
    artifact_url: 'https://kaggle.com/example',
    created_at: '2024-02-29T00:00:00Z',
  },
]

export const DEMO_OPPORTUNITIES: Opportunity[] = [
  {
    opp_id: '1',
    name: 'NASA Space Apps Challenge 2026',
    type: 'competition',
    field_tags: ['cntt', 'stem'],
    scope: 'international',
    is_online: true,
    is_free: true,
    deadline: '2026-10-05',
    source_url: 'https://spaceappschallenge.org',
    admin_verified: true,
    description: 'Hackathon toàn cầu 48 giờ với dữ liệu NASA. Top 10 global được NASA công nhận.',
  },
  {
    opp_id: '2',
    name: 'Olympic Toán Việt Nam 2026',
    type: 'competition',
    field_tags: ['toan', 'stem'],
    scope: 'national',
    is_online: false,
    is_free: true,
    deadline: '2026-06-30',
    source_url: 'https://math.edu.vn',
    admin_verified: true,
    description: 'Kỳ thi Olympic Toán học cấp Quốc gia. Giải vàng được cộng điểm ưu tiên đại học.',
  },
  {
    opp_id: '3',
    name: 'Google Summer of Code 2026',
    type: 'scholarship',
    field_tags: ['cntt', 'stem'],
    scope: 'international',
    is_online: true,
    is_free: true,
    deadline: '2026-04-10',
    source_url: 'https://summerofcode.withgoogle.com',
    admin_verified: true,
    description: 'Chương trình Google tài trợ sinh viên đóng góp cho Open Source. Stipend $3,000-$6,600.',
  },
  {
    opp_id: '4',
    name: 'VinIF Research Fellowship 2026',
    type: 'scholarship',
    field_tags: ['stem', 'cntt', 'toan'],
    scope: 'national',
    is_online: false,
    is_free: true,
    deadline: '2026-07-15',
    source_url: 'https://vinif.org',
    admin_verified: true,
    description: 'Học bổng nghiên cứu cho tài năng trẻ STEM Việt Nam. Hỗ trợ tối đa 50 triệu/năm.',
  },
  {
    opp_id: '5',
    name: 'Kaggle ML Competition — Tabular Q3',
    type: 'competition',
    field_tags: ['cntt', 'toan_thong_ke'],
    scope: 'international',
    is_online: true,
    is_free: true,
    deadline: '2026-12-31',
    source_url: 'https://kaggle.com/competitions',
    admin_verified: true,
    description: 'Series thi Machine Learning hàng tháng. Top 10% được badge vàng Kaggle.',
  },
  {
    opp_id: '6',
    name: 'ICPC Asia Regional 2026',
    type: 'competition',
    field_tags: ['cntt'],
    scope: 'regional',
    is_online: false,
    is_free: true,
    deadline: '2026-09-01',
    source_url: 'https://icpc.global',
    admin_verified: true,
    description: 'Thi lập trình thuật toán đội 3 người. Khu vực châu Á, vé vào Chung kết thế giới.',
  },
]

export const DEMO_MENTORS: MentorProfile[] = [
  {
    mentor_id: '1',
    display_name: 'Trần Văn Dũng',
    school: 'VinUni',
    major: 'Khoa học Máy tính (AI/ML)',
    expertise_tags: ['AI', 'Machine Learning', 'Hồ sơ VinUni', 'SAT Prep'],
    bio: 'Sinh viên năm 3 CNTT VinUni, học bổng 100%. Từng top 40 NASA Space Apps, Kaggle Expert. Sẵn sàng review Portfolio và mock phỏng vấn VinUni.',
    is_active: true,
    verified: true,
    rating: 4.9,
  },
  {
    mentor_id: '2',
    display_name: 'Lê Thị Hương',
    school: 'HUST',
    major: 'Kỹ thuật Máy tính',
    expertise_tags: ['Tư vấn hồ sơ', 'Olympic Tin học', 'HUST Admission', 'C++ Algorithms'],
    bio: 'Cán bộ tuyển sinh HUST kiêm sinh viên năm 4. Giải Nhì Olympic Tin học Quốc gia 2022. Đã tư vấn 50+ học sinh vào HUST và các trường top.',
    is_active: true,
    verified: true,
    rating: 4.8,
  },
  {
    mentor_id: '3',
    display_name: 'Nguyễn Minh Khoa',
    school: 'USTH',
    major: 'Data Science & AI',
    expertise_tags: ['Data Science', 'Python', 'Research', 'USTH Admission'],
    bio: 'Sinh viên năm 4 USTH, học bổng Pháp. Research Assistant tại lab AI của USTH. Chuyên tư vấn hồ sơ nghiên cứu và định hướng Data Science.',
    is_active: true,
    verified: true,
    rating: 4.7,
  },
]

